### ISSUE TITLE
Maybe 'etag' should be 'ETag' for the newest EPF feeds?

### ISSUE THREAD

**Issue by skyforcc** [andreif/epf#1]
Thanks for sharing this tool, it helps a lot.

When I was downloading the EPF file,  the code "if h['etag'] != r.headers['etag']:" leaded to this error:
    KeyError: 'etag'

And then I check the file in the headers_path, I found the correct key should be 'ETag'.

**Comment by andreif** [comment]
Thanks for pointing it, I was sure it always lowers all header names. I will try to fix it. The error never happened to me, so I wonder what is your system and requests version? I missed to mention the requirement in setup.py...

**Comment by skyforcc** [comment]
OS X EI Capitan v10.11
requests 2.8.1
I'm still testing...

**Comment by andreif** [comment]
Hm, we probably should load json as `requests.structures.CaseInsensitiveDict` so the comparison is correct...

**Comment by andreif** [comment]
Aha, I was using it with requests `2.7.0`, so they have changed it in `2.8.0-2.8.1`

**Comment by andreif** [comment]
Do you want to make a pull request for it or I can just push the fix I made locally?

**Comment by andreif** [comment]
@skyforcc Could you try `1.0.3` to see if the issue is resolved?

**Comment by skyforcc** [comment]
You push the fix is OK, I will try now, thx

**Comment by skyforcc** [comment]
File "/Users/**/Downloads/epf/epf/downloader.py", line 171, in log_progress
    t = float(remain) / avg_rate
ZeroDivisionError: float division by zero

There're some othe issues, but they didn't happen for each time, I will try to make them clear half a day later; If I can't fix them, hope for your advices, thanks a lot.

**Comment by andreif** [comment]
Hm, interesting, zero avg_rate I did not expect :smile:
